export const PRICING_PLANS = [
    {
        title: "Starter",
        description: "Great for individuals and small projects.",
        price: "€29",
        period: "month",
        features: [
            "Basic SEO optimization",
            "Social media setup",
            "Individual configuration",
            "No setup, or hidden fees",
            "Team size: 1 user",
            "Standard support: 6 months",
            "Free updates: 6 months",
        ],
        bestChoice: false,
    },
    {
        title: "Professional",
        description: "Perfect for small businesses and growing startups.",
        price: "€49",
        period: "month",
        features: [
            "Advanced SEO strategies",
            "Social media management",
            "Custom configurations",
            "Priority support",
            "Team size: up to 5 users",
            "Premium support: 12 months",
            "Free updates: 12 months",
        ],
        bestChoice: true,
    },
    {
        title: "Enterprise",
        description:
            "Ideal for large organizations seeking comprehensive solutions.",
        price: "€99",
        period: "month",
        features: [
            "Custom SEO campaigns",
            "Full-service social media management",
            "Full customization",
            "24/7 dedicated support",
            "Team size: unlimited users",
            "Premium support: 24 months",
            "Free updates: 24 months",
        ],
        bestChoice: false,
    },
];
