export const REVIEWS = [
    {
        name: "John Doe",
        date: "2024-01-19 11:25:13",
        company: "TechCorp",
        image: "/images/avatar.png",
        rating: 5,
        review: "NovaWave Digital transformed our online presence. Their SEO and social media strategies significantly boosted our visibility and engagement.",
    },
    {
        name: "Jane Smith",
        date: "2024-02-10 09:15:10",
        company: "Startup Inc.",
        image: "/images/avatar.png",
        rating: 5,
        review: "The team at NovaWave Digital is outstanding! Their expertise in digital marketing helped us reach our target audience effectively.",
    },
    {
        name: "Emily Johnson",
        date: "2024-03-05 14:22:45",
        company: "Enterprise Solutions",
        image: "/images/avatar.png",
        rating: 5,
        review: "We are thrilled with the results from NovaWave Digital. Their customized SEO and social media services are top-notch.",
    },
    {
        name: "Michael Brown",
        date: "2024-04-12 10:34:23",
        company: "InnovateTech",
        image: "/images/avatar.png",
        rating: 5,
        review: "NovaWave Digital's innovative approach to digital marketing has greatly improved our brand's online presence. Highly recommend!",
    },
    {
        name: "Samantha Lee",
        date: "2024-05-08 13:47:56",
        company: "Creative Minds",
        image: "/images/avatar.png",
        rating: 5,
        review: "Excellent service and results! NovaWave Digital's SEO and social media strategies have driven substantial growth for our business.",
    },
    {
        name: "Daniel Martinez",
        date: "2024-06-02 16:29:43",
        company: "NextGen Solutions",
        image: "/images/avatar.png",
        rating: 5,
        review: "Professional and effective! NovaWave Digital has significantly improved our website traffic and social media engagement.",
    },
    {
        name: "Jessica Wilson",
        date: "2024-06-14 11:11:00",
        company: "Tech Innovators",
        image: "/images/avatar.png",
        rating: 5,
        review: "Their tailored digital marketing solutions have taken our business to new heights. We are very pleased with NovaWave Digital’s services.",
    },
    {
        name: "David Anderson",
        date: "2024-06-20 14:55:22",
        company: "Smart Solutions",
        image: "/images/avatar.png",
        rating: 5,
        review: "NovaWave Digital's team is knowledgeable and professional. Their strategies have boosted our online presence tremendously.",
    },
];
